### ISSUE TITLE
Incompatible with service-worker-mock 2.0.5

### ISSUE THREAD

**Issue by sdorazio** [udacity/cloudflare-typescript-workers#20]
`service-worker-mock` version 2.0.5 changed the signature for `trigger('fetch', request)` to return a single `Response` instead of `Response[]`. As a result, the type definitions are out of sync depending which version you are running.

**Comment by 13rac1** [comment]
Is this a breaking change in a patch version? Sounds like it. At least it is a simple fix. Thanks!
