### ISSUE TITLE
Consider switching from to edge-mock

### ISSUE THREAD

**Issue by samuelcolvin** [udacity/cloudflare-typescript-workers#33]
Hi, you might consider switching from [`service-worker-mock`](https://github.com/zackargyle/service-workers/tree/master/packages/service-worker-mock) to [`edge-mock`](https://github.com/samuelcolvin/edge-mock) (which I've just built).

Just a suggestion, feel free to close this if you like.

A few advantages of `edge-mock`:
1. [`service-workers`](https://github.com/zackargyle/service-workers) the project which `service-worker-mock` is a part of is no longer maintained.
2. `edge-mock` provides support for KV store mocking out-of-the-box
3. `edge-mock` properly supports `ArrayBuffer` and `ReadableStream` which `service-worker-mock` do does not
4. `edge-mock` has close to 100% test coverage and is written in typescript.
5. All the implementations provided by `edge-mock` are fully compliant with the types they implement in typescript.

**Comment by 13rac1** [comment]
Hi! `edge-mock` has a [hardcoded dependency on @cloudflare/workers-types](https://github.com/samuelcolvin/edge-mock/blob/265a2ad9bb6f9dd4ba3c62a1fab27226c67ba836/package.json#L88) which regretably duplicates the types in this project. Please see #19 I'd prefer to sunset/handoff this project entirely.

**Comment by samuelcolvin** [comment]
Makes sense, thanks
