### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by simplenotezy** [udacity/cloudflare-typescript-workers#34]
How can I set global environment variables accessable on the `env` property?

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/3786627/160253685-13f073e2-bf85-4864-b0e0-6d342b8ae734.png">

**Comment by sodabrew** [comment]
This package was never updated to handle Module-format workers. I'll close this issue as this project will be archived. Please use Cloudflare's package from https://github.com/cloudflare/workers-types
